### ISSUE TITLE
Regex replacement doesn't work in cmd.exe, only in sh.exe

### ISSUE THREAD

**Issue by Boscop** [ChuckDaniels87/rnr#12]
Context (like in the other issue): About a year ago, Diesel changed the name format of the migrations that it generates. I still have many migrations in the old format and want to use `rnr` to rename them into the new format.

At first I tried to run this in cmd.exe:
`rnr -D '(\d{4})(\d{2})(\d{2})(\d{6})' '$1-$2-$3-$4' ./*` in my migrations folder, but it didn't show any matches/replacements, only `This is a DRY-RUN`. 
I also tried with double quotes, but I got the same result (no matches/replacements) :/
(When I execute it in the sh.exe of the Git Shell (powershell) of GitHub Desktop for Windows, it works, but it's very inconvenient..)
Is there a way to make it work in cmd.exe, too?

**Comment by ChuckDaniels87** [comment]
I think the problem here is that `cmd.exe` [does not implements wildcards](https://superuser.com/a/460609/513163). You cannot use '*' (I think it does not support this './' either).

You could try using `-r` (`--recursive flag`) or provide filenames/directories directly.

**Comment by Boscop** [comment]
It also doesn't work:
```
> rnr -D -r "(\d{4})(\d{2})(\d{2})(\d{6})" "$1-$2-$3-$4" .
This is a DRY-RUN
```

Any idea why? :)

**Comment by ChuckDaniels87** [comment]
You are giving `"(\d{4})(\d{2})(\d{2})(\d{6})"` as path instead of `.` to recursive flag. I suppose I should add some feedback for these cases were *input files/recursive* path are not found.

**Comment by Boscop** [comment]
But shouldn't the path be the last arg?

This also doesn't work:
```
> rnr -D -r . "(\d{4})(\d{2})(\d{2})(\d{6})" "$1-$2-$3-$4"
This is a DRY-RUN
```

**Comment by ChuckDaniels87** [comment]
> But shouldn't the path be the last arg?

As stated on `README.md` and `--help`, recursive flag is followed by a `PATH`.

> This also doesn't work:

It works for me on Windows 10 with `cmd.exe` and on Linux with bash and ZSH:
```sh
> rnr -D -r . "(\d{4})(\d{2})(\d{2})(\d{6})" "$1-$2-$3-$4"
This is DRY-RUN
.\12341212123456 -> .\1234-12-12-123456
```
Any additional information you can provide?

**Comment by Boscop** [comment]
I tried that exact same command and it doesn't work for me on Win 8.1.

Btw, it would be more consistent & intuitive if the path was the last arg with the -r flag, just like without it :)

**Comment by ChuckDaniels87** [comment]
> Btw, it would be more consistent & intuitive if the path was the last arg with the -r flag, just like without it :)

I've previously thought about this, but I ended up using the current implementation. Recursive mode only accepts **one** input path. Otherwise, non-recursive mode accepts an indeterminate number of arguments. I will consider the implications of that change and maybe implement it on *v0.2*.

> I tried that exact same command and it doesn't work for me on Win 8.1.

I have no access to a Win 8.1 system to debug this problem. Does it work in Windows Powershell?

**Comment by ChuckDaniels87** [comment]
I've tested on Win 8.1 using `cmd.exe` and it works fine even with several nested directories:
```sh
> rnr -D -r . "(\d{4})(\d{2})(\d{2})(\d{6})" "$1-$2-$3-$4"
This is DRY-RUN
.\12341212123456\12341212123456 -> .\12341212123456\1234-12-12-123456
.\12341212123456 -> .\1234-12-12-123456
```
Tested with all executables in the latest release (GNU/MSVC + i686/x86_64). Are you running the latest version of *RnR* (v0.1.6)?

> Btw, it would be more consistent & intuitive if the path was the last arg with the -r flag, just like without it :)

I made these changes and you were right, it is more intuitive with that syntax now. I have also enabled multiple input path for the recursive mode. You can try these changes in master branch. There are still some issues to fix before next release but this feature is in a working state.

**Comment by ChuckDaniels87** [comment]
@Boscop Any update about this issue?

**Comment by ChuckDaniels87** [comment]
Closed due to inactivity. Feel free to reopen the issue with new information.
