### ISSUE TITLE
[Feature request] Highlight replacements in dry-run mode.

### ISSUE THREAD

**Issue by murlakatamenka** [ChuckDaniels87/rnr#17]
Hi, thanks for `rnr`!

It would be nice to highlight in color what is replaced with what in a dry-run mode. 

Useful cases:
- files / directories with long names (surely human brain parses colors way faster than long symbol sequences, and then you also need to diff both paths!)
- replacement occurs multiple times

That's how `ripgrep` highlights found matches by default, for instance (`rg fn`):

![image](https://user-images.githubusercontent.com/7361274/88822664-d082fb80-d1cc-11ea-8b62-799b0c8651dd.png)

Or another toy example (`echo barfoobar | rg bar --replace baz`):
![image](https://user-images.githubusercontent.com/7361274/88823099-5dc65000-d1cd-11ea-9060-2910339cdc4b.png)

What do you think?

**Comment by ChuckDaniels87** [comment]
Yes, this would be a nice addition to `rnr`. I will take a look at this feature to include it in the next release. Thanks for the feedback!

**Comment by ChuckDaniels87** [comment]
I added a diff feature in the colored version of the output. It is currently in master but I will include it in the next release.

**Comment by murlakatamenka** [comment]
Awesome, thanks!
